apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /fileserver # Nome do compartilhamento
    server: 10.254.36.74 # Ip do servidor de arquivo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver
  resources:
    requests:
      storage: 5Gi